@echo off
mode 100
color 1
echo ...... ......... ......... ......... ......... ......... ......... ........:?JJ?77^... ......... ...
echo ............................................................................5Y????JYY7^. ...........
echo ...........  .. ...........................................................^G????????JYJ^ ..........
echo .......  :~?JY5?.......................................................... ^G?????????7J5?. ........
echo ...... :?YYJ???B7 .........................................................:B????????????55: .......
echo ..... !YJ?7???7YG...........................................................GJ???????????7YP:.......
echo .... ?5?????????B^..........................................................PY7???????????755 ......
echo ....?Y7????????7B! ..........................  .^:......................... JP7????????????7G7 .....
echo ...^G?7????????7G? ....................  !BG5Y7JB5.       ................. 7G7?????????????JG......
echo ....~5J????????7PY .................  .YGPG#5YPPYPPY??7!~^:.  ..............^B??????????????7G! ....
echo .. .:!GJ???????755 .............  .^!J5GGPYYYYYYYYYY55555555J7~:.  ........ :B??????????????75Y ....
echo . 7YYY?????????7YP............ .!J5P55YYYYYYYYYYYYYYYYYYYYYYY555Y?^  ........GJ?????????????7Y5 ....
echo ..5J77??????????JG.........  ^J5P5YYYYYYYYYYYYYYYYYYYYYYYYYYYYPP5PPY!: ..... PY7????????????75Y ....
echo ..5??????????????B: .....  ~5#GP5YYYYYYYYYYYYYYYYYYYYYYYYYYYYG5!~~!7JY?: ... 557????????????7P7 ....
echo . YJ????????????7B!..... :J5?7!?PGYYYYYYYYYYYYYYYYYYYYYYYYYYPG!!!!!!~!?5?. . 5Y7?????????????G:.....
echo . ?Y7???????????7PJ ... !Y?~~!!~!5GYYYYYYYYYYYYYYYYYYYYYYYYYBJ~!!!!~~~~!J5^ .GJ????????????75J .....
echo ..^P?????????????JG... ?Y!!!!!!!!!GPYYYYYYYYYYYYYYYYYYYYYYYY#7!!~!7?J??7~!5!!G??????????JJJYG:......
echo ...JY7???????????7G!  JY~~~!!!~~!~?#YYYYYYYYYYYYYYYYYYYYYYYY#!!!JB@@@@@8#57Y#J7??????7YB?777^ ......
echo ....5J7???????????JG^?Y~?5GB##GY!~~GPYYYYYYYYYYYYYYYYYYYYYY5#!!P@8J~~5@@@@85YP?????????5Y:   .......
echo ... ^5J7??????????7JB57B@@@#55B@#J~YBYYYYYYYYYYYYYYYYYYYYYY5#!Y@@Y   ~@@@@@@YY57???????75G..........
echo .... ^5J7??????????JBJ8@@@@7   Y@@Y7#YYYYYYY555PPPPPPP55YYYY#7#@@85J58@@@@@@#!PY7????7?5Y^ .........
echo ..... .J5?7???????7GYP@@@@@#?~~G@@@?B5YY5GBBBBBBBBBBBBBBBPYY#Y8@@@@@@@@@@@@@8!YB7??7?55!  ..........
echo ....... ~YY?7??????B!B@@@@@@@@@@@@@PGPYGBBBBBBBBBBBBBBBBBBB5B58@@@@@@@@@@@@@Y~G8??J5Y!. ............
echo ........ .!YYJ?7??J#7Y@@@@@@@@@@@@@#PGGBBBBBBBBBBBBBBBBBBBBBB5G@@@@@@@@@@@8J~5B8PY?^  ..............
echo ............~JYYJ??@G!5@@@@@@@@@@@@BYBBBBBBBBBBBBBBBBBBBBBBBPB7G8@@@@@@8BY?JPGY#~. .................
echo ............. :~?Y58BG??P8@@@@@@@@#?5B5#BBBBBBBBBBBBBBBBBB#PYPG55PGGGP55Y5PPYJPP ...................
echo ...............  .:JB5GPYY5PGBBBGP5PGYY5BBBBBBBBBBBBBBBBBB5YYYYY55PPGGGGG5YJYPG~ ...................
echo .................. .PPJY55PGGGGPPP5YJYYJYPBBBBBBBBBBBBBBPYYYY55PPPP5YJ?7?5BP57. ....................
echo ....................:YPP5PG5YY555PPPPPP5555PGGBBB##BBGGPPPPPP5Y?7!~~!7?JJ?!^. ......................
echo ..................... :!JGPJ?7!!~!!!7??JJYYYY555PPP5YJJ??7!!!!!7?YPP?7~^.  .........................
echo ......................    :~!7JYGP5YJ???7777!!!!!!7777??JJYYYYYJG##8~ ..............................
echo ...........................   .5BP5PG8PJYYYYYYY5YYYYJJJ??77!!~!GPYY5B! .............................
echo ............................. 5GJYYYJ5#7~~~~~~YP?~~~~~~!!!!!!!GPJYYY5B:.............................
echo ............................ ~BYYYYYYYPG!!!!!!?G?!!!!!!!!!!!~PGJYYYYJB? ............................
echo ............................ YGYYYYYYYY#J~!!!!?5?P5~!!!!!!!~J#YYYYYYYPG.............................
echo ............................^85YYYYYYYYPG!!!!!!!!Y5~P7!!!!!!BPYYYYYYYY87 ...........................
echo ........................... P8YYYYYYYYYY#7!!!!!!!!YYJ!!!!!~JBYYYYYYYYY##............................
echo .......................... !@BYYYYYYYYYYBY~!!!!!!!~!~!!!!!!BPYYYYYYYYYB8J ..........................
echo ...........................P#PYYYYYYYYYYGP~!!!!!!!!!!!!!!!?#YYYYYYYYYYGG#:..........................
echo ......................... ?G#PYYYYYYYYYY5B!!!!!!!!!!!!!!!~5GYYYYYYYYYYPGGY .........................
echo .................        .G585YYYYYYYYYY5#!!!!!!!!!!!!!!!!B5YYYYYYYYYYPB5#:   ......................
echo ............  ..^!?JJJYJ?5PY85YYYYYYYYYYY#7!!!!!!!!!!!!!!?#YYYYYYYYYYYPBYG5?!~:    .................
echo .........  .~5B##BGP5YY555Y58YYYYYYYYYYYY#J~!!!!!!!!!!!!~PGYYYYYYYYYYYPBYYY55P5Y?~:  .  ............
echo .........?PGPGBPY55B88PJYYYY85YYYYYYYYYYYB5~!!!!!!!!!!!!!#5YYYYYYYYYYYGBYYYYYJYY5PPJ^^~^  ..........
echo .........#8PJJYYYYJYGBB5YYYY85YYYYYYYYYYYGG~!!!!!!!!!!!~J#YYYYYYYYYYYYBGYYYYJP###GGGP8@#J~.. .......
echo ........7BYYYGGBBGPYYJ5#YYYY#PYYYYYYYYYYY5B!!!!!!!!!!!!~PGYYYYYYYYYYYY#5YYYYP###GYJJYY555##G^ ......
echo ...... ~@#YYPBBBBBBPYYJBPYYYBGJYYYYYYYYYY5#7~~~~!!!!!!!!B5YYYYYYYYYYYPBYYYYP#YYYY5PPPP5YY5B8: ......
echo ........JBYY5GBBBBB5YYYB5YYYP#YYYYYYYYYYY5#GPYJ??777777J#YYYYYYYYYYY5#5YYYY85YYYPBBBBBBGYYY8Y.......
echo ....... .JPYYY5PP5YYYJPBYYYYYG#5YYYYYYYYJPB5PGGBGGGGGGG##YYYYYYYYYY5B5YYYYY85YYYGBBBBBBGYJP@G: .....
echo ......... ~YP5555555PB8P55555Y55P5YYYYYYP85!~~!!!!77777J85YYYYYYY5G#G55555YBBYYYYPGGGG5YY5P?........
echo .......... .:!77?J?777~~^::...  !@#55PBB??GY.         !B#P5PPPPB#?~~!7JY5PPG#G55YYYYYY555J^ ........
echo .............      .  .  .. ... ^5~.:~#G  ............^~: ~@B~!GG:      ...::^!?JJYYJJ?~:. .........